#spring:
#  如果在controller中找不到路由
#  就会再静态资源所在目录寻找："classpath:/haha/"
#  配置后会使用haha/index.html
#  web:
#    resources:
#      static-locations: [classpath:/haha/]
#  所有静态资源访问路由都需要家/res/，会导致静态index.html失效
#  mvc:
#    static-path-pattern: /res/**

#rest post请求转put,delete   修改_method HiddenHttpMethodFilter
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmbuild?useUnicode=true&characterEncoding=UTF-8&connectTimeout=1000&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: zjq123
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:/com/qiu/dao/mysql/mapper/xml/*.xml
  type-aliases-package: com.qiu.entity.mysql